<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ChatRoom.aspx.cs" Inherits="ChatRoom" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title>Chat Room</title>

    <link type="text/css" rel="stylesheet" href="Css/Chat.css" />
    <link type="text/css" rel="stylesheet" href="Css/Forms.css" />
    <link type="text/css" rel="stylesheet" href="Css/General.css" />



    <!--Reference the jQuery library. -->
    <script src="/Scripts/jquery-1.10.2.min.js"></script>
    



    <!--Reference the SignalR library. -->
    <script src="/Scripts/jquery.signalR-2.1.2.js"></script>

    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>

    <script type="text/javascript">
        var turn = false;
        var gameOn = false;
        var messageCount = 0;
        var MAX_MESSAGE_COUNT = <%=MAX_MESSAGE_COUNT%>

            $(document).ready(function () {

                var chatHub = $.connection.chatHub;
                registerClientMethods(chatHub);
                $('#txtMessage').prop('disabled', true);
                $.connection.hub.start().done(function () {
                    registerEvents(chatHub)
                    var siteId = <%=siteId%>;
                chatHub.server.connect(siteId);
            });
            });

        function registerEvents(chatHub) {
            $('#btnSend').click(function () {
                if (turn) {
                    var msg = $("#txtMessage").val();
                    if (msg.length > 0) {
                        chatHub.server.sendMessage(msg);
                        $("#txtMessage").val('');
                        turn = false;
                        $('#title').text("Partner's Turn");
                    }

                }
            });
            $('#btnGuessBot').click(function () {
                if (gameOn) {
                    chatHub.server.guessPartnerIsBot();
                    gameOn = false;
                }
            });
            $('#btnGuessHuman').click(function () {
                if (gameOn) {
                    chatHub.server.guessPartnerIsHuman();
                    gameOn = false;
                }
            });

            $("#txtMessage").keypress(function (e) {
                if (e.which == 13) {
                    $('#btnSend').click();
                }
            });
        }

        function registerClientMethods(chatHub) {

            chatHub.client.onConnected = function () {
                $('#title').text('Searching For Partner...');
                chatHub.server.findPartner();
            }
            chatHub.client.onConnectionFailed = function () {
                $('#title').text('Connection Failed');

            }
            chatHub.client.onPartnerJoined = function () {
                $('#title').text('Chat Started!');
                $('#txtMessage').prop('disabled', false);
                gameOn = true;
                turn = true;
            }
            chatHub.client.onPartnerLeft = function () {
                if (messageCount < MAX_MESSAGE_COUNT) {
                    $('#title').text('Partner Disconnected');
                }
                turn = false;
            }

            chatHub.client.onGameOver = function (url) {
                $.connection.hub.stop();
                window.location = url;

            }
            chatHub.client.onMessageReceived = function (msg, isSelfMsg) {
                messageCount++;
                if (messageCount <= MAX_MESSAGE_COUNT) {

                    var sender, color, title;
                    if (isSelfMsg) {
                        sender = '[You]: ';
                        color = '#438bff';
                        title = "Partner's Turn";
                        turn = false;
                    }
                    else {
                        sender = '[?]: ';
                        color = '#FF6760';
                        title = 'Your Turn';
                        turn = true
                    }
                    var content = '<div style ="color:' + color + ';">' +
                        sender + msg + '</div> <br />';
                    $('#content').append(content);

                   
                    $('#title').text(title);
                }
                if (messageCount >= MAX_MESSAGE_COUNT) {
                    turn = false;
                    $('#title').text("Chat's Over, Take a Guess");
                }



            }




        }

    </script>
</head>
<body>
    <a href="Default.aspx"> 
        <img src="Images/home.png" class="homeIcons" width="80"/>
    </a>
    <h1 class="SmallHeadLines" style="margin-bottom:30px">Chat Room</h1>
    <div id="chat" class="chatRoom">
       
            <div id="title">
                Connecting To Server...
            </div>
            <div id="content">
            </div>
            <div id="messageBar">
                <input id="txtMessage" type="text" maxlength="200" />
                <input id="btnSend" class="submitButton" type="button" value="Send" />
            </div>
         <div id="guessButtons">
            <input id="btnGuessBot" class="Buttons" type="button" value="It's a Bot" />
            <input id="btnGuessHuman" class="Buttons" type="button" value="It's a Human" />
        </div>
        </div>
       
    



</body>
</html>
